### ISSUE TITLE
Package causes SwiftUI preview to fail

### ISSUE THREAD

**Issue by anonrig** [onurhuseyincantay/Hover#10]
Due to `canImport(Combine)` statement inside Hover, previews are failing.

**Comment by onurhuseyincantay** [comment]
will take a look thanks :)

**Comment by onurhuseyincantay** [comment]
@anonrig can you also specify which platform it occurs

**Comment by anonrig** [comment]
Xcode beta 6 on an app targeting iOS 14 built with SwiftUI

**Comment by onurhuseyincantay** [comment]
@anonrig  I wasn't able to reproduce this bug see screenshot below.
<img width="720" alt="Screen Shot 2020-09-27 at 11 38 03" src="https://user-images.githubusercontent.com/24936965/94361649-3ea54b00-00b6-11eb-94db-a1f4603a05a1.png">

can you please provide additional steps.

Thanks in advance.

**Comment by onurhuseyincantay** [comment]
Not reproducible see screenshot below.
![IMAGE 2020-09-28 21:03:07](https://user-images.githubusercontent.com/24936965/94474487-02fda480-01ce-11eb-8cb9-86170ba3e2d3.jpg)
