### ISSUE TITLE
WorkType L15  Encodable issue 

### ISSUE THREAD

**Issue by saroar** [onurhuseyincantay/Hover#25]
https://github.com/onurhuseyincantay/Hover/blob/master/Sources/Hover/Types/WorkType.swift#L15

I think it bugs. this is how I fixed

```
public struct AnyEncodable: Encodable {
    public let encodable: Encodable

    public init(_ encodable: Encodable) {
        self.encodable = encodable
    }

    public func encode(to encoder: Encoder) throws {
        try self.encodable.encode(to: encoder)
    }
}

public enum DataType {
    case requestPlain
    case requestData(data: Data)
    case requestParameters(parameters: [String: Any], encoding: JSONEncoder = JSONEncoder())
    case requestWithEncodable(encodable: AnyEncodable)
}
```

**Comment by onurhuseyincantay** [comment]
I don't understand which part is bugy the type that you are passing needs to conform to encodable rather than that there is no requirement. There is also test cases which verifies this can you please specify the problem.

**Comment by saroar** [comment]
how do you use this line? https://github.com/onurhuseyincantay/Hover/blob/master/Sources/Hover/Types/WorkType.swift#L15

I use my own version here how it working now 
https://github.com/AddaMeSPB/AddaMeIOSSwiftUI/blob/master/AddaMeIOS/API/Event/EventAPI.swift#L14https://github.com/AddaMeSPB/AddaMeIOSSwiftUI/blob/master/AddaMeIOS/Event/EventViewModel.swift#L196

```
    var dataType: DataType {
        switch self {
        case .create(let event):
            return .requestWithEncodable(encodable: AnyEncodable(event)) // my own version with extension I share with u 
            return .requestWithEncodable(encodable: event ) // your version does not work when I try 
```

**Comment by onurhuseyincantay** [comment]
@saroar I might know what the problem is I dont think that you need to have an AnyEncodable wrapper will make some changes and provide a branch for you to use. Meanwhile can you please share your sample request; httpBody, content-type and request type with me please.

**Comment by saroar** [comment]
@onurhuseyincantay yes I will do I am using your code but modify some and create my own package the same style code I used before my apps but yes I will it but it will faster if we can live chat with discord or slack if you have please provide me link so I can add u ad friend there for start chat 
alif#1970
my Discord id

**Comment by onurhuseyincantay** [comment]
@saroar I am currently working so I am not available right now but later I can add you 👍
