### ISSUE TITLE
Hover doesn't work on M1 iOS Simulator

### ISSUE THREAD

**Issue by anonrig** [onurhuseyincantay/Hover#27]
Hi @onurhuseyincantay 

I'm receiving the following error on Xcode both on canvas and on simulator.

<img width="400" alt="ScreenShot 2021-04-08 at 16 13 08@2x" src="https://user-images.githubusercontent.com/1935246/114032795-52134900-9885-11eb-80e0-c079c74dbeac.png">

**Comment by onurhuseyincantay** [comment]
will take a look thanks for the report.

**Comment by anonrig** [comment]
any progress @onurhuseyincantay ?

**Comment by onurhuseyincantay** [comment]
Will take a look this afternoon had to cleanup my personal mac to be able to have the latest xcode version :)

**Comment by onurhuseyincantay** [comment]
@anonrig  I will provide a release build in a couple of minutes since I don't have a M1 MacBook it would be nice if you can confirm the fix on your side.

**Comment by anonrig** [comment]
The problem still continues. If you want I can share my screen to help you with the problem? @onurhuseyincantay

**Comment by onurhuseyincantay** [comment]
@anonrig  please make sure that you are using version number 1.0.9

**Comment by anonrig** [comment]
I tried on `master` branch @onurhuseyincantay

**Comment by onurhuseyincantay** [comment]
final solution that the framework was working as expected but there were other libraries which were efecting project configuration.
